### PR TITLE
Split GitCommitProvider and move LoadCommits from prebuild to file build

### LINKED ISSUE #3700: git commit provider is not thread safe
```
2018-11-27T13:55:31.8552675Z System.ArgumentException : The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
2018-11-27T13:55:31.8553039Z Stack Trace:
2018-11-27T13:55:31.8553196Z at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
2018-11-27T13:55:31.8553617Z at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2018-11-27T13:55:31.8553805Z at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2018-11-27T13:55:31.8553923Z at Microsoft.Docs.Build.GitCommitProvider.<SaveCache>b__16_0(Stream stream) in /home/vsts/work/1/s/src/docfx/lib/git/GitCommitProvider.cs:line 204
2018-11-27T13:55:31.8554060Z at Microsoft.Docs.Build.ProcessUtility.<>c__DisplayClass5_0.<WriteFile>b__0() in /home/vsts/work/1/s/src/docfx/lib/ProcessUtility.cs:line 151
2018-11-27T13:55:31.8555942Z at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Func`1 action) in /home/vsts/work/1/s/src/docfx/lib/ProcessUtility.cs:line 184
2018-11-27T13:55:31.8556114Z at Microsoft.Docs.Build.ContributionProvider.LoadCommits(Docset docset) in /home/vsts/work/1/s/src/docfx/build/metadata/ContributionProvider.cs:line 259
2018-11-27T13:55:31.8556835Z at Microsoft.Docs.Build.ContributionProvider.Create(Docset docset, GitHubUserCache cache) in /home/vsts/work/1/s/src/docfx/build/metadata/ContributionProvider.cs:line 32
2018-11-27T13:55:31.8557428Z at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report) in /home/vsts/work/1/s/src/docfx/build/Build.cs:line 30
2018-11-27T13:55:31.8557585Z at Microsoft.Docs.Build.Program.Run(String[] args) in /home/vsts/work/1/s/src/docfx/cli/Program.cs:line 60
2018-11-27T13:55:31.8557817Z at Microsoft.Docs.Build.E2ETest.RunCore(String docsetPath, E2ESpec spec) in /home/vsts/work/1/s/test/docfx.Test/e2e/E2ETest.cs:line 86
2018-11-27T13:55:31.8557984Z at Microsoft.Docs.Build.E2ETest.Run(String name) in /home/vsts/work/1/s/test/docfx.Test/e2e/E2ETest.cs:line 68
```

### PR DESCRIPTION
**Pull request by OsmondJiang**
1. split git commit provider and git commit cache provider
2. combine repository provider and git commit provider
3. save git commit cache at the end of the build
4. remove contribution provider load, make it as inner call of build page, no need to load commits before build
5. make the git commit provider lifetime consistent with build, **be able to be re-used everywhere during one build**
6. Fixes #3700

### CODE REVIEW

File: src/docfx/build/Build.cs [hunk 1]
```diff
@@ -15,48 +15,53 @@ internal static class Build
     {
         public static async Task Run(string docsetPath, CommandLineOptions options, Report report)
         {
-            var errors = new List<Error>();
+            using (var gitCommitProvider = new GitCommitProvider())
```
Comment (superyyrrzz) [inline src/docfx/build/Build.cs]: This provider's lifecycle is expanded from a pre-step to nearly whole build, so that it cannot be exposed earlier. Will this impact performance, especially in the first run when commit cache is not present?

**Comment by yufeih** [comment]
What is the __peak memory usage__ and __build time__ after this change for azure-docs-pr?

File: src/docfx/lib/git/GitCommitCacheProvider.cs [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+            var cacheFilePath = AppData.GetCommitCachePath(repo.Remote);
+            PathUtility.CreateDirectoryFromFilePath(cacheFilePath);
+            return ProcessUtility.WriteFile(cacheFilePath, stream =>
+            {
+                using (var writer = new BinaryWriter(stream))
+                {
+                    writer.Write(commitCache.Count);
+                    foreach (var (file, value) in commitCache)
+                    {
+                        lock (value)
```
Comment (yufeih) [inline src/docfx/lib/git/GitCommitCacheProvider.cs]: I am a little worried that this implicit lock is now split across two places: here and [here](https://github.com/dotnet/docfx/pull/3705/files#diff-89b00415785c16d2d2c79b969013484fR161) and [here](https://github.com/dotnet/docfx/pull/3705/files#diff-89b00415785c16d2d2c79b969013484fR109), also, the signature `ConcurrentDictionary<string, Dictionary<(long commit, long blob), (long[] commitHistory, int lruOrder)>>` leaks too much implementation detail, do you want to consolidate and abstract them as well?

File: src/docfx/lib/git/GitCommitProvider.cs [hunk 3]
```diff
@@ -1,412 +1,74 @@
...
-        private readonly ConcurrentDictionary<string, Lazy<(List<Commit>, Dictionary<long, Commit>)>> _commits;
-
-        // Intern path strings by given each path segment a string ID. For faster string lookup.
-        private readonly ConcurrentDictionary<string, int> _stringPool = new ConcurrentDictionary<string, int>();
-
-        // A giant memory cache of git tree. Key is the `long` form of SHA2 tree hash, value is a string id to git SHA2 hash.
-        private readonly ConcurrentDictionary<long, Dictionary<int, git_oid>> _trees
-                   = new ConcurrentDictionary<long, Dictionary<int, git_oid>>();
+        private readonly ConcurrentDictionary<string, Repository> _repositoryByFolder = new ConcurrentDictionary<string, Repository>();
+        private readonly ConcurrentDictionary<string, Lazy<Task<(FileCommitProvider provider, Repository repo)>>> _commitProviders = new ConcurrentDictionary<string, Lazy<Task<(FileCommitProvider provider, Repository repo)>>>();
```
Comment (yufeih) [inline src/docfx/lib/git/GitCommitProvider.cs]: nit: feels like `_commitProviders` is a superset of `_repositoryByFolder`, maybe one is enough?

File: src/docfx/lib/git/GitCommitProvider.cs [hunk 4]
```diff
@@ -1,412 +1,74 @@
...
         }
 
         public void Dispose()
         {
-            var repo = Interlocked.Exchange(ref _repo, IntPtr.Zero);
-            if (repo != IntPtr.Zero)
+            foreach (var value in _commitProviders.Values)
             {
-                git_repository_free(_repo);
+                value.Value.Result.provider.Dispose();
```
Comment (yufeih) [inline src/docfx/lib/git/GitCommitProvider.cs]: There is probably no need to evaluate `Lazy` if it `IsValueCreated` is false.
Similarly, there is no need to evaluate Task `Result` if the Task isn't completed. Task is a little more complicated, in theory, task could be in running state when dispose if called, and if we choose to not explicitly dispose running tasks, we need to rely on FileCommitProvider finalizers to do the disposable. Unfortunately, `FileCommitProvider` currently do not have a finalizer, so we may need to add that as well.

File: src/docfx/build/Build.cs (hunk 1 above)
Comment (yufeih) [reply src/docfx/build/Build.cs]: This is exactly the structure we are looking for 💯 💯 💯 👍 👍 👍

File: src/docfx/lib/git/FileCommitProvider.cs [hunk 5]
```diff
@@ -0,0 +1,329 @@
...
+            }
+
+            return result.Select(c => c.GitCommit).ToList();
+        }
+
+        public IReadOnlyList<KeyValuePair<string, Dictionary<(long commit, long blob), (long[] commitHistory, int lruOrder)>>> BuildCache()
+        {
+            if (_cacheUpdated)
+            {
+                return _commitCache.ToArray();
```
Comment (yufeih) [inline src/docfx/lib/git/FileCommitProvider.cs]: nit: Do you want to add a comment about why it is changed from `ToList` to `ToArray`?

Comment (OsmondJiang) [reply src/docfx/lib/git/FileCommitProvider.cs]: ok, will add it

---
In reply to: [237942785](https://github.com/dotnet/docfx/pull/3705#discussion_r237942785) [](ancestors = 237942785)

File: src/docfx/lib/git/GitCommitCacheProvider.cs (hunk 2 above)
Comment (live1206) [reply src/docfx/lib/git/GitCommitCacheProvider.cs]: Maybe we can try to resolve this in a later PR? this PR mainly refactors the scope of GitCommitProvider, split out FileCommitProvider and such on, it is fairly big already.

Comment (live1206) [reply src/docfx/lib/git/GitCommitCacheProvider.cs]: Maybe we can try to resolve this in a later PR? this PR mainly refactors the scope of GitCommitProvider, split out FileCommitProvider and such on, it is fairly big already.

File: src/docfx/lib/git/GitCommitProvider.cs (hunk 4 above)
Comment (OsmondJiang) [reply src/docfx/lib/git/GitCommitProvider.cs]: great comment, learned

---
In reply to: [237937253](https://github.com/dotnet/docfx/pull/3705#discussion_r237937253) [](ancestors = 237937253)

File: src/docfx/lib/git/GitCommitProvider.cs (hunk 3 above)
Comment (OsmondJiang) [reply src/docfx/lib/git/GitCommitProvider.cs]: i would like to split them, make them more clear to me.

---
In reply to: [237933739](https://github.com/dotnet/docfx/pull/3705#discussion_r237933739) [](ancestors = 237933739)

**Comment by OsmondJiang** [comment]
i will test it using to local machine

---
In reply to: [443267461](https://github.com/dotnet/docfx/pull/3705#issuecomment-443267461) [](ancestors = 443267461)

File: src/docfx/lib/git/FileCommitProvider.cs [hunk 6]
```diff
@@ -0,0 +1,338 @@
...
+
+        public void Dispose()
+        {
+            var repo = Interlocked.Exchange(ref _repo, IntPtr.Zero);
+            if (repo != IntPtr.Zero)
+            {
+                git_repository_free(_repo);
+            }
+
+            GC.SuppressFinalize(this);
```
Comment (live1206) [inline src/docfx/lib/git/FileCommitProvider.cs]: Seems like we should follow the pattern as below?
https://docs.microsoft.com/en-us/dotnet/api/system.gc.suppressfinalize?view=netframework-4.7.2
https://stackoverflow.com/questions/151051/when-should-i-use-gc-suppressfinalize

File: src/docfx/lib/git/GitCommitProvider.cs [hunk 7]
```diff
@@ -1,412 +1,83 @@
...
-                                    writer.Write(sha);
-                                }
-                            }
-                        }
-                    }
-                }
-            });
         }
 
         public void Dispose()
```
Comment (live1206) [inline src/docfx/lib/git/GitCommitProvider.cs]: Do we still need the `Dispose` method? Since we have implemented the finalizer for `FileCommitProvider`, which will be invoked by GC to free unmanaged resources.

File: src/docfx/lib/git/FileCommitProvider.cs (hunk 6 above)
Comment (OsmondJiang) [reply src/docfx/lib/git/FileCommitProvider.cs]: we are using sealed class, no need follow the complex pattern

File: src/docfx/lib/git/GitCommitProvider.cs (hunk 7 above)
Comment (OsmondJiang) [reply src/docfx/lib/git/GitCommitProvider.cs]: the finalizer is just making sure it finally release the resource

**Comment by yufeih** [comment]
> The build files time:
>
> * with cache:(under 1G)
>   
>   * build files: 44s
>   * convert legacy 1:22s
> * without cache:(5.5G)
>   
>   * build files: 2:52s
>   * legacy 1:30

How does this compare to the result before this change?

File: src/docfx/lib/ParallelUtility.cs [hunk 8]
```diff
@@ -90,7 +90,12 @@ public static async Task ForEach<T>(IEnumerable<T> source, Func<T, Action<T>, Ta
             var total = 0;
             var running = 1; // Always run the virtual root node
 
-            queue = new ActionBlock<(T, bool)>(Run, s_dataflowOptions);
+            queue = new ActionBlock<(T, bool)>(Run, new ExecutionDataflowBlockOptions
```
Comment (yufeih) [inline src/docfx/lib/ParallelUtility.cs]: is this an accidental change?

Comment (OsmondJiang) [reply src/docfx/lib/ParallelUtility.cs]: just for testing, will reverting back
