### PR TITLE
Fix ParallelUtility.ForEach not always run source items

### LINKED ISSUE #2950: Toc href test failed randomly
We have a randome CI test failure on travis:

```
[xUnit.net 00:01:43.0128512]     Run(name: "toc/25. Toc href cann't reference a local file", ordinal: 24) [FAIL]
Failed   Run(name: "toc/25. Toc href cann't reference a local file", ordinal: 24)
Error Message:
 Assert.Equal() Failure
Expected: OrderedEnumerable<String, String> ["build.log", "build.manifest", "docs/f1/a.json", "docs/f1/toc.json", "docs/toc.json"]
Actual:   OrderedEnumerable<String, String> ["build.log", "build.manifest", "docs/f1/toc.json", "docs/toc.json"]  
```

### PR DESCRIPTION
**Pull request by yufeih**
FIxes #2950

### CODE REVIEW

File: src/docfx/lib/ParallelUtility.cs [hunk 1]
```diff
@@ -54,29 +55,29 @@ public static Task ForEach<T>(IEnumerable<T> source, Func<T, Task> action, Actio
...
 
+            queue = new ActionBlock<(T, IEnumerable<T>)>(Run, s_dataflowOptions);
+            queue.Post((default, source));
             return queue.Completion;
 
-            async Task Run(T item)
+            async Task Run((T item, IEnumerable<T> inputs) item)
             {
-                await action(item, Enqueue);
+                if (item.inputs != null)
```
Comment (herohua) [inline src/docfx/lib/ParallelUtility.cs]: >item [](start = 20, length = 4)

`item?.inputs`?

Comment (herohua) [reply src/docfx/lib/ParallelUtility.cs]: or `inputs`?

---
In reply to: [199336848](https://github.com/dotnet/docfx/pull/2976#discussion_r199336848) [](ancestors = 199336848)

File: src/docfx/lib/ParallelUtility.cs [hunk 2]
```diff
@@ -54,29 +54,34 @@ public static Task ForEach<T>(IEnumerable<T> source, Func<T, Task> action, Actio
...
-            var running = 0;
-
-            queue = new ActionBlock<T>(Run, s_dataflowOptions);
-
-            foreach (var item in source)
-            {
-                Enqueue(item);
-            }
+            var total = 0;
+            var running = 1; // Always run the virual root node
```
Comment (superyyrrzz) [inline src/docfx/lib/ParallelUtility.cs]: >virual [](start = 47, length = 6)

virtual?
