### PR TITLE
Fix worktree gitdir too long by shorton git location

### LINKED ISSUE #3628: restore failed with `fatal: '$GIT_DIR' too big`
happens when restore azure-docs-pr https://github.com/OPS-E2E-PPE/azure-docs-pr/tree/docfx-v3-with-fix

logs:
```
Preparing worktree (checking out '584c40929a43baebd45c9ebd2c75b5900e5ef5e5')
fatal: '$GIT_DIR' too big
Restore dependencies done in 7.83s, 00:00:07
git-clone-failed (0,0): Cloning git repository 'https://github.com/Azure-Samples/media-services-dotnet-on-demand-encoding-with-media-encoder-standard' ('584c40929a43baebd45c9ebd2c75b5900e5ef5e5') failed.
```

Related code in git.exe: https://github.com/git/git/blob/d166e6afe5f257217836ef24a73764eba390c58d/setup.c#L662

### PR DESCRIPTION
**Pull request by yufeih**
Fixes #3628 by generating a human readable short directory name for urls

### CODE REVIEW

File: src/docfx/lib/PathUtility.cs [hunk 1]
```diff
@@ -128,6 +131,49 @@ public static void CreateDirectoryFromFilePath(string filePath)
...
+            {
+                url = url.Substring(index);
+            }
+
+            url = url.TrimStart('/', '\\', '.', ':').Trim();
+
+            var result = new StringBuilder();
+
+            // Take the first 5 segments and the surrounding 8 chars in each segment, then remove invalid path chars.
+            foreach (var segment in url.Split(new[] { '/', '\\', ' ', '?', '#' }, StringSplitOptions.RemoveEmptyEntries).Take(5))
```
Comment (superyyrrzz) [inline src/docfx/lib/PathUtility.cs]: What about take the last 5 segments? When downloading from URL, the last part can tell what the file actually is.

Comment (yufeih) [reply src/docfx/lib/PathUtility.cs]: Maybe also use surrounding segments
