### PR TITLE
retry github call

### LINKED ISSUE #3190: GetUserProfileByName throwed OperationCanceledException
OperationCanceledException throwed when building `azure-docs-pr`
Traceback:
```
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\HttpClientAdapter.cs:line 184
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\HttpClientAdapter.cs:line 51
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 635
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 626
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters)
   at Microsoft.Docs.Build.GitHubAccessor.GetUserProfileByName(String name) in D:\workspace\DocFXRelated\docfx\src\docfx\lib\github\GitHubAccessor.cs:line 39
````

Related docs:
 * [octokit/user-content-get-some-data](https://github.com/octokit/octokit.net/blob/master/docs/getting-started.md#user-content-get-some-data)
 * [github-api/possible-github-api-called](https://developer.github.com/v3/search/#search-users)

FYI @superyyrrzz @928PJY

### PR DESCRIPTION
**Pull request by superyyrrzz**
fix #3190

### CODE REVIEW

File: src/docfx/lib/github/GitHubAccessor.cs [hunk 1]
```diff
@@ -96,5 +98,33 @@ public async Task<(Error, string login)> GetLoginByCommit(string repoOwner, stri
                 return (Errors.GitHubApiFailed(apiDetail, ex), null);
             }
         }
+
+        public async Task<(Error, T)> RetryApi<T>(string api, Func<Task<T>> action)
```
Comment (live1206) [inline src/docfx/lib/github/GitHubAccessor.cs]: We also have retry logic within `HttpClientUtility`, which is quite similar to this one, can we abstract the retry logic somewhere to be reused?

Comment (superyyrrzz) [reply src/docfx/lib/github/GitHubAccessor.cs]: Updated. My upcoming PR will update HttpClientUtility to use this soon.
