### PR TITLE
Unshallow repos when fetch with --depth 1 failed.

### LINKED ISSUE #3710: can't add worktree when clone repo with depth 1
git-revparse "committash" and git worktree add don't work.

### PR DESCRIPTION
**Pull request by yufeih**
Fixes #3710

### CODE REVIEW

File: src/docfx/lib/git/GitUtility.cs [hunk 1]
```diff
@@ -254,6 +254,7 @@ private static async Task CloneOrUpdate(string path, string url, IEnumerable<str
             catch (InvalidOperationException ex) when (committishes.Any(rev => ex.Message.Contains(rev)))
             {
                 // Fallback to fetch all branches and tags if the input committish is not supported by fetch
+                depth = depthOne ? "--unshallow" : "";
```
Comment (OsmondJiang) [inline src/docfx/lib/git/GitUtility.cs]: make it full clone/fetch again? so the depth==1 only works for refName and tags?

Comment (yufeih) [reply src/docfx/lib/git/GitUtility.cs]: `depth == 1` only works for branches and tags, you cannot fetch a single with commit hash with git AFAIK.

**Comment by live1206** [comment]
When `CloneOrUpdate` failed in an empty repository, `--unshallow` will break:
```
git  fetch --tags --prune --progress --update-head-ok --unshallow "https://github.com/Azure-Samples/azure-iot-samples-node" +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
fatal: --unshallow on a complete repository does not make sense
```
